### ISSUE TITLE
Please disable DOM localStorage and DOM sessionStorage (supercookies) if you can

### ISSUE THREAD

**Issue by hdatma** [jcs/endless#10]

**Comment by jcs** [comment]
These are auto-swept away from non-whitelisted hosts, so there isn't really any benefit in explicitly blocking them from being set in the first place.

**Comment by hdatma** [comment]
Are tabs sandboxed?

**Comment by jcs** [comment]
Sandboxed from each other? No.

**Comment by hdatma** [comment]
Then the browser allows a server A to set supercookies and any other server B to read them. 
I would simply disable DOM localStorage and DOM sessionStorage instead of managing their content.

**Comment by jcs** [comment]
There is no way to set "supercookies".  The restrictions are defined by the [public suffix list](https://publicsuffix.org/list/public_suffix_list.dat) so server A would only be able to set cookies readable by server B if they are in the same domain.

Once you leave site A, its cookies are swept away unless you have another tab open that is also accessing those cookies.

**Comment by hdatma** [comment]
> There is no way to set "supercookies". 

The last famous words...

P.S. Safari on iOS has both DOM localStorage and DOM sessionStorage closed.
