### ISSUE TITLE
Feature request: close tabs by swiping up in tab view.

### ISSUE THREAD

**Issue by ghost** [jcs/endless#22]
The (X) button for closing tabs is fairly small, so I think it would be a good idea to add a gesture for closing tabs.

**Comment by hdatma** [comment]
+1

**Comment by JRomainG** [comment]
I implemented this feature in a fork if it's of any help.

I made it work by using a custom pan gesture recogniser for the scroll view when choosing a tab. By overriding the scroll view's recogniser, swiping on the sides no longer works, so I implemented that back.

~~A visual issue left is that the tab is partially hidden when it arrives at the top of the screen by what I assume is the toolbar~~ The tabScroller stopped before the top of the screen, [tabScroller setClipsToBounds:NO] fixes this.
