### ISSUE TITLE
support HPKP

### ISSUE THREAD

**Issue by jcs** [jcs/endless#25]
https://projects.dm.id.lv/Public-Key-Pins_test

UIWebView does not get this for free like HSTS (and it's not supported in Safari either), so this would need to be implemented in Endless itself.

**Comment by heri16** [comment]
Seems to be a really good addition.

**Comment by jcs** [comment]
Maybe not: https://groups.google.com/a/chromium.org/forum/m/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ
