### ISSUE TITLE
Feature request: 3d touch menu support on application launcher with new window/

### ISSUE THREAD

**Issue by alanhoyle** [jcs/endless#33]
A nice feature would be to have the 3d touch menu in the application launcher do things in the app.  Two options that I imagine would be useful would be "new browser tab" and "clear all data."

See below for an example project from Apple for this kind of thing. 

https://developer.apple.com/library/content/samplecode/ApplicationShortcuts/Introduction/Intro.html#//apple_ref/doc/uid/TP40016545

**Comment by peteygao** [comment]
Yes please, this feature would be useful. Also it would be amazing if there was a similar 3D push to preview feature like in the stock Safari (but I can understand this would be much more work).

**Comment by jcs** [comment]
These are both implemented in 183afefdb and 592c51cc8.  The force-touch action on a link will open it in a new tab.  The force-touch options on the launch icon can clear all data or add a new tab.
