### ISSUE TITLE
injected.js: FakeLocation.propery.get is broken

### ISSUE THREAD

**Issue by adam-p** [jcs/endless#35]
As can be [seen here](https://github.com/jcs/endless/blob/80d21bfedddd21cdde551ba4f04e843f84d77068/Endless/Resources/injected.js#L205), the `FakeLocation` property getters seem to be copy-pasted from the setter, including the reference to the `v` param, which doesn't exist in the getter.

Additionally, in `WebViewTab.m` there's no handler for `endlessipc://fakeWindow.getLocationParam`, so even if JS didn't crash it wouldn't go anywhere. (Here's the [`setLocationParam` handler](https://github.com/jcs/endless/blob/80d21bfedddd21cdde551ba4f04e843f84d77068/Endless/Resources/injected.js#L205).)

**Comment by jcs** [comment]
4928855adee2c6449db39b9ff19e75adc1143f2f
