### ISSUE TITLE
bookmarks

### ISSUE THREAD

**Issue by spiritloveroot** [jcs/endless#36]
really, this is the main thing holding this app back. 

1. is it possible to have the share sheet menu in this app or is that too much a security risk?

2. if too much security risk, is it possible to add a text based bookmarking system? are there any open source versions of this? 

perhaps linking bookmarks to an exportable txt file with the ability to write notes above the bookmark. of course tagging or foldering would be great but at least some simple bookmarking system which is exportable outside of the app would be great. 

3. a "find on page" function

**Comment by jcs** [comment]
If you open iTunes and connect to your device, the bookmarks plist file is exported in the File Sharing section.  From there you can convert it to whatever format you want.
