### ISSUE TITLE
Open in Endless

### ISSUE THREAD

**Issue by heri16** [jcs/endless#38]
Add extension to open in endless browser from safari page.

**Comment by jcs** [comment]
I've created an extension to be able to do this, but I don't know if Apple will allow it through App Review.  Opening URLs from a share extension is not directly supported and Apple probably has a reason for that, so the way this extension has to do it is a hack.

But I'll submit this with the next update and see whether they approve it.  If not, this will have to be an option that is only enabled if you compile the app yourself.

There is an app in the App Store called [Opener](http://www.opener.link/) which opens URLs from Safari this way and it already supports Endless, which is promising.

**Comment by jcs** [comment]
Well, they approved it. Version 2.0 with this share extension is available in the App Store 👍
