### ISSUE TITLE
Please disable SSLv3 if you can

### ISSUE THREAD

**Issue by hdatma** [jcs/endless#5]

**Comment by jcs** [comment]
I looked into this a while back and I don't think it's possible without having to do all of the requests manually with some other library.

Hopefully Apple will disable this universally in some version of iOS which will automatically affect UIWebViews and thus Endless.

**Comment by jcs** [comment]
[CKHTTPConnection](https://github.com/OnionBrowser/iOS-OnionBrowser/blob/master/OnionBrowser/ConnectionKit/CKHTTPConnection.m) that OnionBrowser uses might be useful for this kind of stuff.

**Comment by hdatma** [comment]
He is not using Apple's ssl library, which is good:
https://github.com/OnionBrowser/iOS-OnionBrowser/blob/master/build-libssl.sh

Do the same, with a twist: at lines 139 and 143, add the following:
"no-ssl2 no-ssl3 no-ssl3-method no-rc4".

**Comment by jcs** [comment]
I believe that is only used for building Tor.  For actual SSL connections it is still using Apple's libraries, which I would prefer to do rather than having to bring in OpenSSL/LibreSSL since those have their own constant security problems.

**Comment by hdatma** [comment]
Apple's SSL is not devoid of problems and limitations. 
OpenSSL is a bit messy. 
I use LibreSSL everywhere...
