### ISSUE TITLE
Make a new app icon

### ISSUE THREAD

**Issue by jcs** [jcs/endless#50]
Apple [rejected](https://github.com/jcs/endless/commit/9f0572e9ce812d41a528d692837ae8700bb73627) the 1.8 update because the app icon was too similar to Safari's (after having the same icon since 2015) so the icon was changed to remove the compass part which makes it less recognizable as a web browser.

Perhaps some helpful creative person can design a new icon.

**Comment by JRomainG** [comment]
I had 2 ideas based on the icon you currently have:

![endless icon radar](https://user-images.githubusercontent.com/7504819/33503635-c722b1ce-d6e4-11e7-8428-7352218e9454.png)
<p align="center">Inspired by a radar / planet thought<p/>
<br/><br/><br/><br/><br/><br/><br/><br/>

![endless icon infinity](https://user-images.githubusercontent.com/7504819/33503639-ca9dd180-d6e4-11e7-87e6-5c25dd44fb47.png)
<p align="center">An obvious reference to the name of the app<p/>

<br/><br/><br/>
I haven't checked how they look in smaller sizes on mobile devices

**Comment by jcs** [comment]
Sticking with the current icon for now, thanks though
