### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by auliausu** [jcs/endless#53]
Dear Developers
i have made some contribution for your project by creating new logo, maybe you will be interest to it ;)
you check on this link of blog 👍:
https://steemit.com/utopian-io/@auliausu/new-logo-proposal-for-endless-browser

![cover](https://user-images.githubusercontent.com/9031884/34595599-f71bcca2-f20b-11e7-8ae3-99381f9e368e.png)
![presentation](https://user-images.githubusercontent.com/9031884/34595605-fc718fca-f20b-11e7-83bb-490a1b803da7.png)

**Comment by jcs** [comment]
Sticking with the current icon for now, thanks though
