### ISSUE TITLE
Request: Keepass support (open source password manager)

### ISSUE THREAD

**Issue by sunjam** [jcs/endless#55]
I was wondering if you would consider adding support for keepass password databases, which are fully open source + easy to self host.  [Here is a quick write-up from the EFF on how to use keepass.](https://ssd.eff.org/en/module/how-use-keepassxc)

**Comment by jcs** [comment]
Integrating a password manager is beyond the scope of this app, but if there is a Keepass iOS app that supports the same extension mechanisms that 1Password and Bitwarden do, it will [automatically show up](https://github.com/jcs/endless/commit/d4150580c52e147d8c99d53da10b7447ec359a3a) now for auto-filling.
