### ISSUE TITLE
Request: Nextcloud Bookmarks (open source bookmark manager)

### ISSUE THREAD

**Issue by sunjam** [jcs/endless#57]
It would fantastic to sync iOS Bookmarks between Endless and [Nextcloud Bookmarks](https://github.com/nextcloud/bookmarks) using their new [REST API](https://github.com/nextcloud/bookmarks/blob/master/appinfo/routes.php).
    
Here is [issue #116 on Onion Browser](https://github.com/mtigas/OnionBrowser/issues/116), which is based off your excellent browser.  Maybe @marcelklehr can advise.

**Comment by jcs** [comment]
This does not need to live inside Endless and should exist as a separate app that provides an extension for browsers to call out to like 1Password and Bitwarden do for password management.
