### ISSUE TITLE
Please disable mixed content if you can

### ISSUE THREAD

**Issue by hdatma** [jcs/endless#6]

**Comment by jcs** [comment]
I'm assuming you mean mixed-mode content, with a page loaded over https trying to access resources over http.  In that case, this was already implemented long ago.

**Comment by hdatma** [comment]
No, I am referring to images and websockets.

**Comment by jcs** [comment]
A Content-Security-Policy header could be added to the response in URLInterceptor, which would prevent certain things from trying to load.

`img-src 'none';` would block images and `connect-src 'none';` would block websockets (but also ajax).

A setting could be added which sets how strict this policy would be by default, and probably a way to override policies per-domain like the cookie whitelisting.
