### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by ahmeterbay** [jcs/endless#60]
hi..
sometimes i design logo on utopian.io and i saw your open source project application..
ı wanted desıgn a logo for your app..
ı thınk u wıll lıke it.
plss check ıt and feedback me-llike or not :))

https://utopian.io/utopian-io/@ahmeterbay/endless-browser-logo-icon-proposal

**Comment by jcs** [comment]
Sticking with the current icon for now, thanks though
