### ISSUE TITLE
Basic auth prompts blocked

### ISSUE THREAD

**Issue by fffergal** [jcs/endless#71]
I log in to [SSO][sso] accounts with [ADFS][adfs]. On the public internet it shows a form for username and password. When on the VPN or local network, it only shows a blank page on Endless. I think the difference is ADFS uses a basic auth pop up login box when on the local network, as confirmed on other browsers. Could Endless be blocking these auth prompts?

[sso]: https://en.m.wikipedia.org/wiki/Single_sign-on
[adfs]: https://en.wikipedia.org/wiki/Active_Directory_Federation_Services

**Comment by jcs** [comment]
Basic auth is supported and seems to be working fine here.  I just tested it with the Basic Authentication test at https://jigsaw.w3.org/HTTP/

**Comment by fffergal** [comment]
That one example could be more complicated than that then. Could well be a website problem, nothing to do with Endless. Which is a shame becauase I need to use it every day.

**Comment by jcs** [comment]
If you are able to find a publicly accessible test case, I can try to debug what's going on.  Otherwise I'm not sure how to fix this.
